using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using Outlook = Microsoft.Office.Interop.Outlook;

namespace OutlookTools.Digest
{
    /// <summary>
    /// OutlookTools — Daily Digest Generator
    /// Generates a morning summary of:
    /// - New emails since last check
    /// - Pending follow-ups
    /// - Unread counts
    /// - Top senders of the day
    /// - Flagged items
    /// 
    /// Output: On-screen dashboard (optionally auto-send as email).
    /// </summary>
    public static class DailyDigestGenerator
    {
        /// <summary>
        /// Generate digest for the current day.
        /// </summary>
        public static DigestData Generate(Outlook.Application app)
        {
            var data = new DigestData();
            Outlook.NameSpace session = app.Session;

            try
            {
                // --- Inbox stats ---
                Outlook.Folder inbox = session.GetDefaultFolder(
                    Outlook.OlDefaultFolders.olFolderInbox) as Outlook.Folder;
                if (inbox != null)
                {
                    data.TotalUnread = inbox.UnReadItemCount;
                    data.TodayNew = CountTodayEmails(inbox);
                    data.TodaySenders = GetTopSendersToday(inbox);
                    data.FlaggedCount = CountFlagged(inbox);
                }

                // --- Sent stats ---
                Outlook.Folder sent = session.GetDefaultFolder(
                    Outlook.OlDefaultFolders.olFolderSentMail) as Outlook.Folder;
                if (sent != null)
                {
                    data.SentToday = CountTodaySent(sent);
                }

                // --- Follow-up pending ---
                data.PendingFollowUps = FollowUp.FollowUpTracker.GetPending().Count;

                // --- Overdue follow-ups ---
                data.OverdueFollowUps = FollowUp.FollowUpTracker.GetPending()
                    .Count(x => x.Status == FollowUp.FollowUpStatus.Overdue);

                data.GeneratedAt = DateTime.Now;
            }
            catch (Exception ex)
            {
                ThisAddIn.LogDebug("DailyDigest.Generate: " + ex.Message);
            }

            return data;
        }

        /// <summary>
        /// Format digest as HTML email body.
        /// </summary>
        public static string FormatAsHtml(DigestData data)
        {
            string overdueWarning = data.OverdueFollowUps > 0
                ? $"<p style='color:red;font-weight:bold;'>⚠️ {data.OverdueFollowUps} follow-up(s) are OVERDUE!</p>"
                : "";

            string sendersList = data.TodaySenders.Count > 0
                ? "<ul>" + string.Join("", data.TodaySenders.Select(s => $"<li>{s.Key}: {s.Value} emails</li>")) + "</ul>"
                : "<p>No emails today yet.</p>";

            return $@"
<html dir='rtl'>
<body style='font-family:Segoe UI,sans-serif;color:#1e293b;padding:20px;'>
<h2 style='color:#3b82f6;'>📊 OutlookTools — Daily Digest</h2>
<p style='color:#64748b;'>Generated: {data.GeneratedAt:yyyy-MM-dd HH:mm}</p>

{overdueWarning}

<table style='border-collapse:collapse;width:100%;margin:15px 0;'>
<tr style='background:#f1f5f9;'>
<td style='padding:10px;border:1px solid #e2e8f0;font-weight:bold;'>📬 New Emails Today</td>
<td style='padding:10px;border:1px solid #e2e8f0;font-size:1.3em;color:#3b82f6;'>{data.TodayNew}</td>
</tr>
<tr>
<td style='padding:10px;border:1px solid #e2e8f0;font-weight:bold;'>📨 Sent Today</td>
<td style='padding:10px;border:1px solid #e2e8f0;'>{data.SentToday}</td>
</tr>
<tr style='background:#f1f5f9;'>
<td style='padding:10px;border:1px solid #e2e8f0;font-weight:bold;'>📬 Total Unread</td>
<td style='padding:10px;border:1px solid #e2e8f0;'>{data.TotalUnread}</td>
</tr>
<tr>
<td style='padding:10px;border:1px solid #e2e8f0;font-weight:bold;'>🚩 Flagged</td>
<td style='padding:10px;border:1px solid #e2e8f0;'>{data.FlaggedCount}</td>
</tr>
<tr style='background:#f1f5f9;'>
<td style='padding:10px;border:1px solid #e2e8f0;font-weight:bold;'>⏳ Pending Follow-ups</td>
<td style='padding:10px;border:1px solid #e2e8f0;'>{data.PendingFollowUps}</td>
</tr>
<tr>
<td style='padding:10px;border:1px solid #e2e8f0;font-weight:bold;'>🔴 Overdue Follow-ups</td>
<td style='padding:10px;border:1px solid #e2e8f0;color:red;'>{data.OverdueFollowUps}</td>
</tr>
</table>

<h3>Top Senders Today:</h3>
{sendersList}

<hr style='border:none;border-top:1px solid #e2e8f0;margin:20px 0;'>
<p style='color:#94a3b8;font-size:0.85em;'>Generated by OutlookTools (Open Source) — All data is local, nothing uploaded.</p>
</body>
</html>";
        }

        // === Helpers ===

        private static int CountTodayEmails(Outlook.Folder folder)
        {
            int count = 0;
            try
            {
                Outlook.Items items = folder.Items;
                items.Sort("[ReceivedTime]", true);
                var today = DateTime.Today;

                foreach (object obj in items)
                {
                    if (!(obj is Outlook.MailItem mail)) continue;
                    try
                    {
                        if (mail.ReceivedTime < today) break;
                        count++;
                    }
                    finally { ReleaseCom(mail); }
                }
            }
            catch { }
            return count;
        }

        private static int CountTodaySent(Outlook.Folder folder)
        {
            int count = 0;
            try
            {
                Outlook.Items items = folder.Items;
                items.Sort("[SentOn]", true);
                var today = DateTime.Today;

                foreach (object obj in items)
                {
                    if (!(obj is Outlook.MailItem mail)) continue;
                    try
                    {
                        if (mail.SentOn < today) break;
                        count++;
                    }
                    finally { ReleaseCom(mail); }
                }
            }
            catch { }
            return count;
        }

        private static int CountFlagged(Outlook.Folder folder)
        {
            int count = 0;
            try
            {
                foreach (object obj in folder.Items)
                {
                    if (!(obj is Outlook.MailItem mail)) continue;
                    try
                    {
                        if (mail.FlagStatus != Outlook.OlFlagStatus.olNoFlag)
                            count++;
                    }
                    finally { ReleaseCom(mail); }
                }
            }
            catch { }
            return count;
        }

        private static Dictionary<string, int> GetTopSendersToday(Outlook.Folder folder)
        {
            var senders = new Dictionary<string, int>();
            try
            {
                Outlook.Items items = folder.Items;
                items.Sort("[ReceivedTime]", true);
                var today = DateTime.Today;

                foreach (object obj in items)
                {
                    if (!(obj is Outlook.MailItem mail)) continue;
                    try
                    {
                        if (mail.ReceivedTime < today) break;
                        string name = mail.SenderName ?? "Unknown";
                        if (senders.ContainsKey(name))
                            senders[name]++;
                        else
                            senders[name] = 1;
                    }
                    finally { ReleaseCom(mail); }
                }
            }
            catch { }

            return senders.OrderByDescending(x => x.Value)
                .Take(5)
                .ToDictionary(x => x.Key, x => x.Value);
        }

        private static void ReleaseCom(object obj)
        {
            try
            {
                if (obj != null && System.Runtime.InteropServices.Marshal.IsComObject(obj))
                    System.Runtime.InteropServices.Marshal.ReleaseComObject(obj);
            }
            catch { }
        }
    }

    public class DigestData
    {
        public int TodayNew { get; set; }
        public int SentToday { get; set; }
        public int TotalUnread { get; set; }
        public int FlaggedCount { get; set; }
        public int PendingFollowUps { get; set; }
        public int OverdueFollowUps { get; set; }
        public Dictionary<string, int> TodaySenders { get; set; } = new Dictionary<string, int>();
        public DateTime GeneratedAt { get; set; }
    }
}
